# -*- coding: utf-8 -*-
"""task1_script.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kjzDe9fQDefEgringueYyk1ySnEOxvRm
"""

!pip install torch
!pip install transformers
!pip install sentencepiece

from transformers import PegasusTokenizer, PegasusForConditionalGeneration

# Model ve tokenizer yükleme
def load_pegasus_tokenizer():
    return PegasusTokenizer.from_pretrained("google/pegasus-xsum")

def load_pegasus_model():
    return PegasusForConditionalGeneration.from_pretrained("google/pegasus-xsum")

# Özetleme fonksiyonu
def pegasus_summarize(text, tokenizer, model):
    # Metni modele uygun hale getirme
    inputs = tokenizer(text, return_tensors="pt", max_length=1024, truncation=True)

    # Modeli çalıştırma
    summary_ids = model.generate(
        inputs['input_ids'], max_length=150, min_length=40, do_sample=True,
        temperature=1.5, top_k=50, top_p=0.95, repetition_penalty=1.2,
        length_penalty=2.0, num_return_sequences=1
    )

    # Özet metnini çözümleme
    summary = tokenizer.decode(summary_ids[0], skip_special_tokens=True)
    return summary

# Tokenizer ve Model'i yükleyin
tokenizer = load_pegasus_tokenizer()
model = load_pegasus_model()

# Kullanıcıdan dosya yüklemesini isteme
from google.colab import files  # files modülünü import ediyoruz
uploaded = files.upload()

# Yüklenen dosyayı okuma
for file_name in uploaded.keys():
    with open(file_name, 'r') as file:
        sample_text = file.read()

# Özetleme işlemi
summary = pegasus_summarize(sample_text, tokenizer, model)

# Özetlenen metni yazdırma
print("\nÖzet:")
print(summary)

# Özetlenen metni bir dosyaya kaydetme
output_file_name = "output_task1.txt"
with open(output_file_name, 'w') as output_file:
    output_file.write(summary)

# Kullanıcıya dosya indirme linki sağlama
files.download(output_file_name)